POST http://localhost:5000/account/register
content-type: application/json

{
    "name": "test",
    "surname": "test",
    "email": "test3@test.com",
    "password": "password",
    "passwordConfirm": "password"
}
