POST http://localhost:5000/account/register
content-type: application/json

{
    "name": "",
    "surname": "test",
    "email": "test@test.com",
    "password": "password",
    "passwordConfirm": ""
}
